[tmifm_maily]
title = "차우진의 TMI.FM ─ 메일리"
url = "https://maily.so/draft.briefing"
entrySelector = "div[class='grid gap-2 lg:gap-4'] div[class='w-full h-auto flex flex-col flex border border-gray-200']"
titleSelector = "div[class='text-gray-900 font-bold text-base lg:text-xl whitespace-normal truncate-2-lines']"
linkSelector = "a"
contentSelector = "p[class='text-gray-700 text-sm lg:text-base truncate-2-lines']"
imageSelector = "div[class='flex-shrink-0 w-full h-20 lg:h-32 flex-none bg-cover text-center overflow-hidden']"
waitUntil = "networkidle"

[tmifm_naverpremiumcontents]
title = "TMI.FM 팬덤랩스 ─ 네이버 프리미엄콘텐츠"
url = "https://contents.premium.naver.com/tmifm/labs/contents"
entrySelector = "ul.content_list._CONTENT_LIST li.content_item.as_thumb"
titleSelector = "strong.content_title"
linkSelector = "a.content_text_link"
contentSelector = "a.content_category"
imageSelector = "a.content_thumb img"
waitUntil = "networkidle"

[tmifm_kakaotalk]
title = "TMI.FM 뮤직랩스 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_nuEns"
entrySelector = "ul.list_news li"
titleSelector = "span.txt_g"
linkSelector = "a.link_item"
waitUntil = "networkidle"

[woojin_brunch]
title = "차우진 ─ 브런치"
url = "https://brunch.co.kr/@woojin#articles"
entrySelector = "ul.list_article.list_post1 li.animation_up"
titleSelector = "a.link_post strong.tit_subject"
linkSelector = "a.link_post"
contentSelector = "div.post_desc"
imageSelector = "div.post_thumb img"
waitUntil = "networkidle"

[zenerate_glivery]
title = "제너레이트 ─ 글리버리"
url = "https://zenerate.glivery.co.kr/"
entrySelector = "div.full-width div.card-container.full-width"
titleSelector = "div.main-card-title.ellipsis.cursor-pointer a"
linkSelector = "div.main-card-title.ellipsis.cursor-pointer a"
contentSelector = "div.main-card-summary.ellipsis.cursor-pointer"
imageSelector = "div.q-img__image.absolute-full"
waitUntil = "networkidle"

[zenerate_linktree]
title = "제너레이트 ─ 링크트리"
url = "https://linktr.ee/Re_nez0"
entrySelector = "div[class='sc-bdfBwQ sc-gsTCUz bcrzgk bhdLno'] div[class='sc-bdfBwQ LyLIy'] div[class='sc-bdfBwQ pkAuV']"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[vop_bandobyul]
title = "민중의소리 ─ 서정민갑의 수요뮤직"
url = "http://www.vop.co.kr/list_tag.php?tag=%EC%84%9C%EC%A0%95%EB%AF%BC%EA%B0%91%EC%9D%98%20%EC%88%98%EC%9A%94%EB%AE%A4%EC%A7%81&page=1"
entrySelector = "div.list-body ul li"
titleSelector = "h4"
linkSelector = "a"
contentSelector = "p.list-date"
waitUntil = "networkidle"
